apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "gatekeeper.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    gatekeeper.sh/system: "yes"
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: gatekeeper-webhook-service
  namespace: '{{ .Release.Namespace }}'
spec:
  
  ports:
  - name: https-webhook-server
    port: 443
    targetPort: webhook-server
{{- if .Values.service }}
{{- if .Values.service.healthzPort }}
  - name: http-webhook-healthz
    port: {{ .Values.service.healthzPort }}
    targetPort: healthz
      {{- end }}
  {{- end }}
  {{- if .Values.service }}
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
    {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "gatekeeper.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    gatekeeper.sh/operation: webhook
    gatekeeper.sh/system: "yes"
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
