{{- if .Values.resourceQuota }}
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "gatekeeper.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    gatekeeper.sh/system: "yes"
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: gatekeeper-critical-pods
  namespace: '{{ .Release.Namespace }}'
spec:
  hard:
    pods: {{ .Values.podCountLimit }}
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - {{ .Values.controllerManager.priorityClassName }}
      - {{ .Values.audit.priorityClassName }}
{{- end }}
